### Register User API
POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json

{
    "username" : "piter2",
    "password": "rahasia",
    "name": "Piter Pangaribuan"
}

### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username" : "piter2",
    "password": "rahasia"
}

### GET Current User API
GET http://localhost:8000/api/users/current
Authorization: 9b8264ef-3dbe-44f7-9d5c-118e264c5312
Accept: application/json

### UPDATE Current User API
PATCH http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 9b8264ef-3dbe-44f7-9d5c-118e264c5312

{
    "name" : "piter",
    "password": "update"
}

### LOGOUT Current User API
DELETE http://localhost:8000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 9b8264ef-3dbe-44f7-9d5c-118e264c5312

### CREATE Contact API
POST http://localhost:8000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

{
    "first_name" : "piter4",
    "last_name" : "png",
    "email" : "piter@test.com",
    "phone" : "1232"
}

### GET Contact API
GET http://localhost:8000/api/contacts/445
Content-Type: application/json
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

### UPDATE Contact API
PUT http://localhost:8000/api/contacts/445
Content-Type: application/json
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

{
    "first_name" : "Piter",
    "last_name" : "Png",
    "email" : "piter@test.com",
    "phone" : "1232"
}

### DELETE Contact API
DELETE http://localhost:8000/api/contacts/445
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

### SEARCH Contact API
GET http://localhost:8000/api/contacts?page=2&size=2
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

### CREATE Address API
POST http://localhost:8000/api/contacts/448/addresses
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62
Content-Type: application/json

{
    "street" : "tidak ada",
    "city" : "batam",
    "province" : "kerpi",
    "country" : "ind",
    "postal_code" : "1232"
}

### GET Address API
GET http://localhost:8000/api/contacts/448/addresses/27
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

### UPDATE Address API
PUT http://localhost:8000/api/contacts/448/addresses/27
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62
Content-Type: application/json

{
    "street" : "melati",
    "city" : "batam",
    "province" : "kerpi",
    "country" : "ind",
    "postal_code" : "1232"
}

### DELETE Address API
DELETE http://localhost:8000/api/contacts/448/addresses/27
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62

### GET List Address API
GET http://localhost:8000/api/contacts/448/addresses
Accept: application/json
Authorization: b61ee9c0-276e-40d1-bc15-ac83f6fd9b62
